### ISSUE TITLE
Support IdentityServer4

### ISSUE THREAD

**Issue by MattCotterellNZ** [Soluto/IdentityServer.Contrib.JsonWebKeyAdapter#1]
`SigningKeyService` currently implements the interface for `ISigningKeyService` in IdentityServer3, but it does not work if you try to register this against IdentitiyServer4's version of this interface (using DI). Can we make `SigningKeyService` support both versions of this interface so I can use this class when using IdentityServer4?

**Comment by omerlh** [comment]
Hey, 
That sound great idea. Maybe it will be better to separate it to 2 different packages (like in any other related libraries). I didn't do that because I am using IdentitiyServer3 currently, but you are very welcome to create a pull request if you'd like.
Also, I think it will be better to separate it to 2 packages so each package will be dependent on a single version of IdentityServer.
What do you think?
Omer

**Comment by MattCotterellNZ** [comment]
While it might be technically possible to shim in both interfaces into the one implementation, I think you're right, having two libraries might be the best approach. I'm having a problem with a lot of copy/pasting going on between two libraries in my own `IdentityServer*.Contrib.*` packages however, so a "common" package between these two might not go amiss either (see https://github.com/MattCotterellNZ/IdentityServer.Contrib.AzureKeyVaultTokenSigningService/issues/10 ). Thoughts?

**Comment by omerlh** [comment]
Yes, you are probably right. Will you have time to work on that?
Thanks!

**Comment by MattCotterellNZ** [comment]
Sorry, I've been a little bit flat out this month! I won't be able to tackle it for at least another week but I can try after that! :)

**Comment by omerlh** [comment]
Ok thats great :)

**Comment by ebickle** [comment]
This project hasn't seen any activity in many years. Closing out all existing issues, marking it as deprecated, and archiving this repository.
